// Code generated by "go run ./cmd/reset"; DO NOT EDIT.

package models

// Reset возвращает ShortenBatchRequestItem в начальное состояние.
func (x *ShortenBatchRequestItem) Reset() {
	if x == nil {
		return
	}
	x.CorrelationID = ""
	x.OriginalURL = ""
}

// Reset возвращает ShortenBatchResponseItem в начальное состояние.
func (x *ShortenBatchResponseItem) Reset() {
	if x == nil {
		return
	}
	x.CorrelationID = ""
	x.ShortURL = ""
}

// Reset возвращает UserURLItem в начальное состояние.
func (x *UserURLItem) Reset() {
	if x == nil {
		return
	}
	x.ShortURL = ""
	x.OriginalURL = ""
}
