package main

import (
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/tools/go/packages"
)

const (
	// generateMarker — комментарий над структурой, включающий генерацию.
	generateMarker = "generate:reset"
	// resetMethod — имя генерируемого метода.
	resetMethod = "Reset"
	// genFileName — файл с методами всех помеченных структур пакета.
	genFileName = "reset.gen.go"
	// receiverName — имя приёмника в сгенерированном методе.
	receiverName = "x"
	// zeroHelperName — хелпер обнуления через дженерик: избавляет
	// сгенерированный файл от импортов чужих пакетов.
	zeroHelperName = "resetZero"
	// blankField — поле-пустышка, к которому нельзя обратиться по имени.
	blankField = "_"
	// scanPattern — шаблон загрузки пакетов текущего модуля и ниже.
	scanPattern = "./..."
	// genFilePerm — права на сгенерированный файл.
	genFilePerm = 0o644
	// genHeader предупреждает, что файл не редактируют руками.
	genHeader = "// Code generated by \"go run ./cmd/reset\"; DO NOT EDIT."
)

// packagesMode перечисляет данные, нужные генератору: имена и файлы пакетов,
// разобранные деревья и результаты вывода типов.
const packagesMode = packages.NeedName | packages.NeedFiles | packages.NeedSyntax |
	packages.NeedTypes | packages.NeedTypesInfo

// target — структура, помеченная к генерации.
type target struct {
	obj    *types.TypeName
	strct  *types.Struct
	pkg    *packages.Package
	dir    string
	helper string
	// generated — файлы прошлого запуска: объявленные в них методы Reset
	// исчезнут после перезаписи, поэтому опираться на них нельзя
	generated map[string][]byte
}

// generate сканирует пакеты начиная с dir и записывает файлы с методами Reset.
// Возвращает пути записанных файлов.
func generate(dir string) ([]string, error) {
	// прошлые результаты запоминаются, но пока остаются на месте: код, который
	// вызывает сгенерированные методы, без них не разберётся
	previous, err := collectGenerated(dir)
	if err != nil {
		return nil, err
	}

	pkgs, err := loadPackages(dir)
	if err != nil {
		return nil, err
	}

	var targets []target
	for _, pkg := range pkgs {
		found, err := markedStructs(pkg, previous)
		if err != nil {
			return nil, err
		}
		targets = append(targets, found...)
	}

	// структура, помеченная к генерации, получит Reset в этом же запуске,
	// поэтому вложенные поля такого типа сбрасываются вызовом метода
	marked := make(map[*types.TypeName]bool, len(targets))
	for _, t := range targets {
		marked[t.obj] = true
	}

	byDir := make(map[string][]target)
	for _, t := range targets {
		byDir[t.dir] = append(byDir[t.dir], t)
	}

	written := make([]string, 0, len(byDir))
	fresh := make(map[string][]byte, len(byDir))
	for dir, dirTargets := range byDir {
		path, err := filepath.Abs(filepath.Join(dir, genFileName))
		if err != nil {
			return nil, fmt.Errorf("путь %s: %w", dir, err)
		}
		src, err := renderFile(dirTargets, marked)
		if err != nil {
			return nil, errors.Join(fmt.Errorf("%s: %w", path, err), restoreGenerated(previous))
		}
		fresh[path] = src
	}

	// сначала проверяются все пути и только потом идёт запись: наткнуться на
	// чужой файл в середине — значит оставить дерево наполовину обновлённым
	for path := range fresh {
		if err := checkWritable(path, previous); err != nil {
			return nil, err
		}
	}

	var created []string
	for path, src := range fresh {
		// путь запоминается до записи: прерванный WriteFile тоже оставляет файл
		if _, existed := previous[path]; !existed {
			created = append(created, path)
		}
		if err := os.WriteFile(path, src, genFilePerm); err != nil {
			return nil, errors.Join(fmt.Errorf("запись %s: %w", path, err), rollback(created, previous))
		}
		written = append(written, path)
	}

	// у пакетов, где маркеры сняли, прошлый файл больше не нужен. Каталоги
	// пакетов с несошедшимися типами не трогаются: там структура могла не
	// разобраться, и её методы удалились бы вместе с рабочим файлом
	unsure := uncertainDirs(pkgs)
	stale := make(map[string][]byte)
	for path, src := range previous {
		if _, ok := fresh[path]; ok {
			continue
		}
		if unsure[filepath.Dir(path)] {
			continue
		}
		stale[path] = src
	}
	if err := removePaths(stale); err != nil {
		return nil, err
	}

	sort.Strings(written)

	return written, nil
}

// loadPackages разбирает пакеты модуля.
//
// Ошибки вывода типов не считаются фатальными: до первого запуска генератора
// код, который вызывает ещё не сгенерированный Reset, типы не проходит — именно
// ради него генератор и запускают. Структуры при этом разбираются полностью.
// А вот сломанный синтаксис останавливает работу: по обрывкам дерева нельзя
// понять, какие структуры помечены, и генератор молча выбросил бы их методы.
func loadPackages(dir string) ([]*packages.Package, error) {
	pkgs, err := packages.Load(&packages.Config{Mode: packagesMode, Dir: dir}, scanPattern)
	if err != nil {
		return nil, fmt.Errorf("загрузка пакетов: %w", err)
	}
	for _, pkg := range pkgs {
		for _, pkgErr := range pkg.Errors {
			if pkgErr.Kind == packages.ParseError {
				return nil, fmt.Errorf("пакет %s: %w", pkg.PkgPath, pkgErr)
			}
		}
		// пакет с ошибками, из которого не удалось получить ни одного дерева,
		// разобрать нечем: молча пропустить его — значит потерять его методы
		if len(pkg.Errors) > 0 && len(pkg.Syntax) == 0 {
			return nil, fmt.Errorf("пакет %s: %w", pkg.PkgPath, pkg.Errors[0])
		}
	}
	return pkgs, nil
}

// uncertainDirs возвращает каталоги пакетов, чьи типы не сошлись: разбор таких
// пакетов неполон, и делать выводы об отсутствии маркеров по ним нельзя.
func uncertainDirs(pkgs []*packages.Package) map[string]bool {
	dirs := make(map[string]bool)
	for _, pkg := range pkgs {
		if len(pkg.Errors) == 0 {
			continue
		}
		for _, file := range pkg.Syntax {
			dir, err := filepath.Abs(filepath.Dir(pkg.Fset.Position(file.Pos()).Filename))
			if err != nil {
				continue
			}
			dirs[dir] = true
		}
	}
	return dirs
}

// collectGenerated читает ранее сгенерированные файлы во всём дереве каталогов.
// Чужие файлы с тем же именем не учитываются: признак свой — заголовок.
func collectGenerated(root string) (map[string][]byte, error) {
	found := make(map[string][]byte)
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || entry.Name() != genFileName {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("чтение %s: %w", path, err)
		}
		if !strings.HasPrefix(string(data), genHeader) {
			return nil
		}
		// пути приводятся к абсолютным: имена новых файлов приходят из позиций
		// разбора и всегда абсолютны, а обход дерева повторяет форму аргумента
		abs, err := filepath.Abs(path)
		if err != nil {
			return fmt.Errorf("путь %s: %w", path, err)
		}
		found[abs] = data
		return nil
	})
	if err != nil {
		return nil, err
	}
	return found, nil
}

// checkWritable не даёт затереть чужой файл: перезаписывается только то, что
// генератор писал сам, а имя reset.gen.go мог занять и человек.
func checkWritable(path string, generated map[string][]byte) error {
	if _, ours := generated[path]; ours {
		return nil
	}
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("%s: файл занят чужим кодом, генератор его не перезаписывает", path)
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("проверка %s: %w", path, err)
	}
	return nil
}

// removePaths удаляет перечисленные файлы, не останавливаясь на первой ошибке:
// остальные файлы всё равно нужно убрать.
func removePaths(files map[string][]byte) error {
	var errs []error
	for path := range files {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			errs = append(errs, fmt.Errorf("удаление %s: %w", path, err))
		}
	}
	return errors.Join(errs...)
}

// rollback отменяет частично выполненное обновление: только что созданные файлы
// удаляются, прежние возвращаются на место.
func rollback(created []string, previous map[string][]byte) error {
	var errs []error
	for _, path := range created {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			errs = append(errs, fmt.Errorf("откат %s: %w", path, err))
		}
	}
	errs = append(errs, restoreGenerated(previous))
	return errors.Join(errs...)
}

// restoreGenerated возвращает файлы в исходное состояние: генератор не должен
// оставлять проект несобираемым, если сам завершился с ошибкой.
func restoreGenerated(files map[string][]byte) error {
	var errs []error
	for path, data := range files {
		if err := os.WriteFile(path, data, genFilePerm); err != nil {
			errs = append(errs, fmt.Errorf("восстановление %s: %w", path, err))
		}
	}
	return errors.Join(errs...)
}

// markedStructs собирает структуры пакета, над которыми стоит маркер генерации.
// Набор generated нужен, чтобы отличить наш прошлый результат от чужого кода.
func markedStructs(pkg *packages.Package, generated map[string][]byte) ([]target, error) {
	var found []target
	for _, file := range pkg.Syntax {
		dir := filepath.Dir(pkg.Fset.Position(file.Pos()).Filename)
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok || !hasMarker(genDecl.Doc, typeSpec.Doc) {
					continue
				}
				obj, ok := pkg.TypesInfo.Defs[typeSpec.Name].(*types.TypeName)
				if !ok {
					continue
				}
				strct, ok := obj.Type().Underlying().(*types.Struct)
				if !ok {
					continue
				}
				// метод, написанный руками, генератор не заменяет: два
				// объявления Reset сделали бы пакет несобираемым
				if hasOwnReset(obj, pkg, generated) {
					return nil, fmt.Errorf("%s.%s: метод %s уже объявлен, маркер %s лишний",
						pkg.PkgPath, obj.Name(), resetMethod, generateMarker)
				}
				found = append(found, target{
					obj:       obj,
					strct:     strct,
					pkg:       pkg,
					dir:       dir,
					helper:    helperName(pkg),
					generated: generated,
				})
			}
		}
	}
	return found, nil
}

// hasOwnReset сообщает, написан ли метод Reset руками. Метод из прошлого
// запуска генератора таковым не считается: он будет перезаписан. Совпадения по
// имени файла мало — чужой reset.gen.go без нашего заголовка трогать нельзя,
// поэтому проверяется принадлежность к собранному набору.
func hasOwnReset(obj *types.TypeName, pkg *packages.Package, generated map[string][]byte) bool {
	named, ok := obj.Type().(*types.Named)
	if !ok {
		return false
	}
	method, _, _ := types.LookupFieldOrMethod(types.NewPointer(named), true, pkg.Types, resetMethod)
	fn, ok := method.(*types.Func)
	if !ok {
		return false
	}
	path, err := filepath.Abs(pkg.Fset.Position(fn.Pos()).Filename)
	if err != nil {
		// не смогли опознать файл — считаем метод чужим, так безопаснее
		return true
	}
	_, ours := generated[path]
	return !ours
}

// hasMarker ищет маркер в комментариях объявления типа: он может стоять и над
// одиночным type, и над строкой внутри блока type (...).
func hasMarker(groups ...*ast.CommentGroup) bool {
	for _, group := range groups {
		if group == nil {
			continue
		}
		for _, comment := range group.List {
			if strings.Contains(comment.Text, generateMarker) {
				return true
			}
		}
	}
	return false
}

// helperName подбирает имя хелпера, не занятое в пакете: к базовому имени
// добавляется числовой суффикс, пока имя не окажется свободным.
func helperName(pkg *packages.Package) string {
	name := zeroHelperName
	for i := 2; pkg.Types.Scope().Lookup(name) != nil; i++ {
		name = zeroHelperName + strconv.Itoa(i)
	}
	return name
}

// receiver печатает приёмник метода. У обобщённой структуры перечисляются
// параметры типа: func (x *Box[T]) Reset().
func receiver(obj *types.TypeName) string {
	named, ok := obj.Type().(*types.Named)
	if !ok || named.TypeParams().Len() == 0 {
		return obj.Name()
	}
	params := named.TypeParams()
	names := make([]string, 0, params.Len())
	for i := 0; i < params.Len(); i++ {
		names = append(names, params.At(i).Obj().Name())
	}
	return obj.Name() + "[" + strings.Join(names, ", ") + "]"
}

// renderFile собирает содержимое reset.gen.go для одного пакета.
func renderFile(targets []target, marked map[*types.TypeName]bool) ([]byte, error) {
	sort.Slice(targets, func(i, j int) bool { return targets[i].obj.Name() < targets[j].obj.Name() })

	var body strings.Builder
	helperUsed := false
	for _, t := range targets {
		stmts, used := methodBody(t, marked)
		helperUsed = helperUsed || used

		fmt.Fprintf(&body, "\n// %s возвращает %s в начальное состояние.\n", resetMethod, t.obj.Name())
		fmt.Fprintf(&body, "func (%s *%s) %s() {\n", receiverName, receiver(t.obj), resetMethod)
		fmt.Fprintf(&body, "if %s == nil {\nreturn\n}\n", receiverName)
		for _, stmt := range stmts {
			body.WriteString(stmt)
			body.WriteString("\n")
		}
		body.WriteString("}\n")
	}

	var out strings.Builder
	out.WriteString(genHeader)
	out.WriteString("\n\npackage ")
	out.WriteString(targets[0].pkg.Types.Name())
	out.WriteString("\n")
	out.WriteString(body.String())

	if helperUsed {
		helper := targets[0].helper
		fmt.Fprintf(&out, "\n// %s присваивает значению нулевое значение его типа.\n", helper)
		fmt.Fprintf(&out, "func %s[T any](v *T) {\nvar zero T\n*v = zero\n}\n", helper)
	}

	src, err := format.Source([]byte(out.String()))
	if err != nil {
		return nil, fmt.Errorf("форматирование: %w", err)
	}
	return src, nil
}

// methodBody возвращает операторы сброса всех полей структуры и признак того,
// что понадобился хелпер обнуления.
func methodBody(t target, marked map[*types.TypeName]bool) (stmts []string, helperUsed bool) {
	for i := 0; i < t.strct.NumFields(); i++ {
		field := t.strct.Field(i)
		// поле-пустышка недоступно по имени, сбрасывать его нечем
		if field.Name() == blankField {
			continue
		}
		selector := receiverName + "." + field.Name()
		stmt, used := resetStatement(selector, field.Type(), t, marked)
		if stmt == "" {
			continue
		}
		helperUsed = helperUsed || used
		stmts = append(stmts, stmt)
	}
	return stmts, helperUsed
}

// resetStatement строит оператор сброса одного значения по правилам инкремента.
func resetStatement(selector string, typ types.Type, t target, marked map[*types.TypeName]bool) (string, bool) {
	// указатель сбрасывает не сам себя, а значение под ним, и только если оно есть
	if ptr, ok := typ.Underlying().(*types.Pointer); ok {
		var (
			inner string
			used  bool
		)
		if hasReset(typ, t, marked) {
			inner = selector + "." + resetMethod + "()"
		} else {
			inner, used = resetStatement(deref(selector), ptr.Elem(), t, marked)
		}
		if inner == "" {
			return "", false
		}
		return fmt.Sprintf("if %s != nil {\n%s\n}", selector, inner), used
	}

	if hasReset(typ, t, marked) {
		return selector + "." + resetMethod + "()", false
	}

	switch under := typ.Underlying().(type) {
	case *types.Basic:
		return fmt.Sprintf("%s = %s", selector, zeroLiteral(under)), false
	case *types.Slice:
		// длина сбрасывается, ёмкость сохраняется: буфер переиспользуется
		return fmt.Sprintf("%s = %s[:0]", selector, selector), false
	case *types.Map:
		return fmt.Sprintf("clear(%s)", selector), false
	default:
		return fmt.Sprintf("%s(%s)", t.helper, addressOf(selector)), true
	}
}

// deref оборачивает выражение разыменованием, сохраняя приоритет операций:
// (*x.f)[:0] — это срез значения, а *x.f[:0] — срез указателя.
func deref(selector string) string {
	return "(*" + selector + ")"
}

// addressOf берёт адрес выражения, схлопывая &(*p) обратно в p.
func addressOf(selector string) string {
	if inner, ok := strings.CutPrefix(selector, "(*"); ok {
		if inner, ok := strings.CutSuffix(inner, ")"); ok {
			return inner
		}
	}
	return "&" + selector
}

// hasReset сообщает, есть ли у типа метод Reset без аргументов и возвращаемых
// значений. Структуры, помеченные маркером, тоже считаются: их методы
// появятся в этом же запуске генератора.
//
// Интерфейсы исключены: значение интерфейса по умолчанию nil, и вызов метода на
// нём паникует, поэтому такое поле обнуляется, а не сбрасывается.
func hasReset(typ types.Type, t target, marked map[*types.TypeName]bool) bool {
	if _, ok := typ.Underlying().(*types.Interface); ok {
		return false
	}
	if named, ok := typ.(*types.Named); ok && marked[named.Obj()] {
		return true
	}
	if ptr, ok := typ.Underlying().(*types.Pointer); ok {
		if named, ok := ptr.Elem().(*types.Named); ok && marked[named.Obj()] {
			return true
		}
	}

	obj, _, _ := types.LookupFieldOrMethod(typ, true, t.pkg.Types, resetMethod)
	fn, ok := obj.(*types.Func)
	if !ok {
		return false
	}
	sig, ok := fn.Type().(*types.Signature)
	if !ok || sig.Params().Len() != 0 || sig.Results().Len() != 0 {
		return false
	}
	// метод из прошлого результата генерации не в счёт: маркер могли снять, и
	// тогда после перезаписи такого метода не станет
	path, err := filepath.Abs(t.pkg.Fset.Position(fn.Pos()).Filename)
	if err != nil {
		return false
	}
	_, fromGenerated := t.generated[path]
	return !fromGenerated
}

// zeroLiteral возвращает литерал нулевого значения примитивного типа.
func zeroLiteral(basic *types.Basic) string {
	switch info := basic.Info(); {
	case info&types.IsBoolean != 0:
		return "false"
	case info&types.IsString != 0:
		return `""`
	case info&types.IsComplex != 0:
		return "0i"
	case info&types.IsNumeric != 0:
		return "0"
	default:
		// unsafe.Pointer и прочие нечисловые примитивы
		return "nil"
	}
}
