package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/tools/go/packages"
)

const (
	// generateMarker — комментарий над структурой, включающий генерацию.
	generateMarker = "generate:reset"
	// resetMethod — имя генерируемого метода.
	resetMethod = "Reset"
	// genFileName — файл с методами всех помеченных структур пакета.
	genFileName = "reset.gen.go"
	// receiverName — имя приёмника в сгенерированном методе.
	receiverName = "x"
	// zeroHelperName — хелпер обнуления через дженерик: избавляет
	// сгенерированный файл от импортов чужих пакетов.
	zeroHelperName = "resetZero"
	// blankField — поле-пустышка, к которому нельзя обратиться по имени.
	blankField = "_"
	// scanPattern — шаблон загрузки пакетов текущего модуля и ниже.
	scanPattern = "./..."
	// genFilePerm — права на сгенерированный файл.
	genFilePerm = 0o644
	// genHeader предупреждает, что файл не редактируют руками.
	genHeader = "// Code generated by \"go run ./cmd/reset\"; DO NOT EDIT."
)

// packagesMode перечисляет данные, нужные генератору: имена и файлы пакетов,
// разобранные деревья и результаты вывода типов.
const packagesMode = packages.NeedName | packages.NeedFiles | packages.NeedSyntax |
	packages.NeedTypes | packages.NeedTypesInfo

// target — структура, помеченная к генерации.
type target struct {
	obj    *types.TypeName
	strct  *types.Struct
	pkg    *packages.Package
	dir    string
	helper string
	// generated — файлы прошлого запуска: объявленные в них методы Reset
	// исчезнут после перезаписи, поэтому опираться на них нельзя
	generated map[string][]byte
}

// generate сканирует пакеты начиная с dir и записывает файлы с методами Reset.
// Возвращает пути записанных файлов.
func generate(dir string) ([]string, error) {
	// прошлые результаты запоминаются, но пока остаются на месте: код, который
	// вызывает сгенерированные методы, без них не разберётся
	previous, err := collectGenerated(dir)
	if err != nil {
		return nil, err
	}

	pkgs, err := loadPackages(dir)
	if err != nil {
		return nil, err
	}

	var targets []target
	for _, pkg := range pkgs {
		found, err := markedStructs(pkg, previous)
		if err != nil {
			return nil, err
		}
		targets = append(targets, found...)
	}

	// структура, помеченная к генерации, получит Reset в этом же запуске,
	// поэтому вложенные поля такого типа сбрасываются вызовом метода
	marked := make(map[*types.TypeName]bool, len(targets))
	for _, t := range targets {
		marked[t.obj] = true
	}

	byDir := make(map[string][]target)
	for _, t := range targets {
		byDir[t.dir] = append(byDir[t.dir], t)
	}

	written := make([]string, 0, len(byDir))
	fresh := make(map[string][]byte, len(byDir))
	for dir, dirTargets := range byDir {
		path, err := filepath.Abs(filepath.Join(dir, genFileName))
		if err != nil {
			return nil, fmt.Errorf("путь %s: %w", dir, err)
		}
		src, err := renderFile(dirTargets, marked)
		if err != nil {
			return nil, errors.Join(fmt.Errorf("%s: %w", path, err), restoreGenerated(previous))
		}
		fresh[path] = src
	}

	// сначала проверяются все пути и только потом идёт запись: наткнуться на
	// чужой файл в середине — значит оставить дерево наполовину обновлённым
	for path := range fresh {
		if err := checkWritable(path, previous); err != nil {
			return nil, err
		}
	}

	var created []string
	for path, src := range fresh {
		// путь запоминается до записи: прерванный WriteFile тоже оставляет файл
		if _, existed := previous[path]; !existed {
			created = append(created, path)
		}
		if err := os.WriteFile(path, src, genFilePerm); err != nil {
			return nil, errors.Join(fmt.Errorf("запись %s: %w", path, err), rollback(created, previous))
		}
		written = append(written, path)
	}

	// у пакетов, где маркеры сняли, прошлый файл больше не нужен. Каталоги
	// пакетов с несошедшимися типами не трогаются: там структура могла не
	// разобраться, и её методы удалились бы вместе с рабочим файлом
	unsure := uncertainDirs(pkgs)
	stale := make(map[string][]byte)
	for path, src := range previous {
		if _, ok := fresh[path]; ok {
			continue
		}
		if unsure[filepath.Dir(path)] {
			continue
		}
		stale[path] = src
	}
	if err := removePaths(stale); err != nil {
		return nil, err
	}

	sort.Strings(written)

	return written, nil
}

// loadPackages разбирает пакеты модуля.
//
// Ошибки вывода типов не считаются фатальными: до первого запуска генератора
// код, который вызывает ещё не сгенерированный Reset, типы не проходит — именно
// ради него генератор и запускают. Структуры при этом разбираются полностью.
// А вот сломанный синтаксис останавливает работу: по обрывкам дерева нельзя
// понять, какие структуры помечены, и генератор молча выбросил бы их методы.
func loadPackages(dir string) ([]*packages.Package, error) {
	pkgs, err := packages.Load(&packages.Config{Mode: packagesMode, Dir: dir}, scanPattern)
	if err != nil {
		return nil, fmt.Errorf("загрузка пакетов: %w", err)
	}
	for _, pkg := range pkgs {
		for _, pkgErr := range pkg.Errors {
			if pkgErr.Kind == packages.ParseError {
				return nil, fmt.Errorf("пакет %s: %w", pkg.PkgPath, pkgErr)
			}
		}
		// пакет с ошибками, из которого не удалось получить ни одного дерева,
		// разобрать нечем: молча пропустить его — значит потерять его методы
		if len(pkg.Errors) > 0 && len(pkg.Syntax) == 0 {
			return nil, fmt.Errorf("пакет %s: %w", pkg.PkgPath, pkg.Errors[0])
		}
	}
	return pkgs, nil
}

// uncertainDirs возвращает каталоги пакетов, чьи типы не сошлись: разбор таких
// пакетов неполон, и делать выводы об отсутствии маркеров по ним нельзя.
func uncertainDirs(pkgs []*packages.Package) map[string]bool {
	dirs := make(map[string]bool)
	for _, pkg := range pkgs {
		if len(pkg.Errors) == 0 {
			continue
		}
		for _, file := range pkg.Syntax {
			dir, err := filepath.Abs(filepath.Dir(pkg.Fset.Position(file.Pos()).Filename))
			if err != nil {
				continue
			}
			dirs[dir] = true
		}
	}
	return dirs
}

// collectGenerated читает ранее сгенерированные файлы во всём дереве каталогов.
// Чужие файлы с тем же именем не учитываются: признак свой — заголовок.
func collectGenerated(root string) (map[string][]byte, error) {
	found := make(map[string][]byte)
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || entry.Name() != genFileName {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("чтение %s: %w", path, err)
		}
		if !strings.HasPrefix(string(data), genHeader) {
			return nil
		}
		// пути приводятся к абсолютным: имена новых файлов приходят из позиций
		// разбора и всегда абсолютны, а обход дерева повторяет форму аргумента
		abs, err := filepath.Abs(path)
		if err != nil {
			return fmt.Errorf("путь %s: %w", path, err)
		}
		found[abs] = data
		return nil
	})
	if err != nil {
		return nil, err
	}
	return found, nil
}

// checkWritable не даёт затереть чужой файл: перезаписывается только то, что
// генератор писал сам, а имя reset.gen.go мог занять и человек.
func checkWritable(path string, generated map[string][]byte) error {
	if _, ours := generated[path]; ours {
		return nil
	}
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("%s: файл занят чужим кодом, генератор его не перезаписывает", path)
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("проверка %s: %w", path, err)
	}
	return nil
}

// removePaths удаляет перечисленные файлы, не останавливаясь на первой ошибке:
// остальные файлы всё равно нужно убрать.
func removePaths(files map[string][]byte) error {
	var errs []error
	for path := range files {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			errs = append(errs, fmt.Errorf("удаление %s: %w", path, err))
		}
	}
	return errors.Join(errs...)
}

// rollback отменяет частично выполненное обновление: только что созданные файлы
// удаляются, прежние возвращаются на место.
func rollback(created []string, previous map[string][]byte) error {
	var errs []error
	for _, path := range created {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			errs = append(errs, fmt.Errorf("откат %s: %w", path, err))
		}
	}
	errs = append(errs, restoreGenerated(previous))
	return errors.Join(errs...)
}

// restoreGenerated возвращает файлы в исходное состояние: генератор не должен
// оставлять проект несобираемым, если сам завершился с ошибкой.
func restoreGenerated(files map[string][]byte) error {
	var errs []error
	for path, data := range files {
		if err := os.WriteFile(path, data, genFilePerm); err != nil {
			errs = append(errs, fmt.Errorf("восстановление %s: %w", path, err))
		}
	}
	return errors.Join(errs...)
}

// markedStructs собирает структуры пакета, над которыми стоит маркер генерации.
// Набор generated нужен, чтобы отличить наш прошлый результат от чужого кода.
func markedStructs(pkg *packages.Package, generated map[string][]byte) ([]target, error) {
	var found []target
	for _, file := range pkg.Syntax {
		dir := filepath.Dir(pkg.Fset.Position(file.Pos()).Filename)
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok || !hasMarker(genDecl.Doc, typeSpec.Doc) {
					continue
				}
				obj, ok := pkg.TypesInfo.Defs[typeSpec.Name].(*types.TypeName)
				if !ok {
					continue
				}
				strct, ok := obj.Type().Underlying().(*types.Struct)
				if !ok {
					continue
				}
				// метод, написанный руками, генератор не заменяет: два
				// объявления Reset сделали бы пакет несобираемым
				if hasOwnReset(obj, pkg, generated) {
					return nil, fmt.Errorf("%s.%s: метод %s уже объявлен, маркер %s лишний",
						pkg.PkgPath, obj.Name(), resetMethod, generateMarker)
				}
				found = append(found, target{
					obj:       obj,
					strct:     strct,
					pkg:       pkg,
					dir:       dir,
					helper:    helperName(pkg),
					generated: generated,
				})
			}
		}
	}
	return found, nil
}

// hasOwnReset сообщает, написан ли метод Reset руками. Метод из прошлого
// запуска генератора таковым не считается: он будет перезаписан. Совпадения по
// имени файла мало — чужой reset.gen.go без нашего заголовка трогать нельзя,
// поэтому проверяется принадлежность к собранному набору.
func hasOwnReset(obj *types.TypeName, pkg *packages.Package, generated map[string][]byte) bool {
	named, ok := obj.Type().(*types.Named)
	if !ok {
		return false
	}
	method, _, _ := types.LookupFieldOrMethod(types.NewPointer(named), true, pkg.Types, resetMethod)
	fn, ok := method.(*types.Func)
	if !ok {
		return false
	}
	path, err := filepath.Abs(pkg.Fset.Position(fn.Pos()).Filename)
	if err != nil {
		// не смогли опознать файл — считаем метод чужим, так безопаснее
		return true
	}
	_, ours := generated[path]
	return !ours
}

// hasMarker ищет маркер в комментариях объявления типа: он может стоять и над
// одиночным type, и над строкой внутри блока type (...).
func hasMarker(groups ...*ast.CommentGroup) bool {
	for _, group := range groups {
		if group == nil {
			continue
		}
		for _, comment := range group.List {
			if strings.Contains(comment.Text, generateMarker) {
				return true
			}
		}
	}
	return false
}

// helperName подбирает имя хелпера, не занятое в пакете: к базовому имени
// добавляется числовой суффикс, пока имя не окажется свободным.
func helperName(pkg *packages.Package) string {
	name := zeroHelperName
	for i := 2; pkg.Types.Scope().Lookup(name) != nil; i++ {
		name = zeroHelperName + strconv.Itoa(i)
	}
	return name
}

// receiverType собирает выражение типа приёмника. У обобщённой структуры
// перечисляются параметры типа: func (x *Box[T]) Reset().
func receiverType(obj *types.TypeName) ast.Expr {
	name := ast.NewIdent(obj.Name())
	named, ok := obj.Type().(*types.Named)
	if !ok || named.TypeParams().Len() == 0 {
		return name
	}
	params := named.TypeParams()
	args := make([]ast.Expr, 0, params.Len())
	for i := 0; i < params.Len(); i++ {
		args = append(args, ast.NewIdent(params.At(i).Obj().Name()))
	}
	if len(args) == 1 {
		return &ast.IndexExpr{X: name, Index: args[0]}
	}
	return &ast.IndexListExpr{X: name, Indices: args}
}

// renderFile собирает содержимое reset.gen.go для одного пакета. Объявления
// строятся деревом разбора и печатаются go/format; комментарии к ним идут
// отдельными строками, потому что go/printer расставляет комментарии по
// позициям узлов, а у построенного дерева позиций нет.
func renderFile(targets []target, marked map[*types.TypeName]bool) ([]byte, error) {
	sort.Slice(targets, func(i, j int) bool { return targets[i].obj.Name() < targets[j].obj.Name() })

	var out bytes.Buffer
	fmt.Fprintf(&out, "%s\n\npackage %s\n", genHeader, targets[0].pkg.Types.Name())

	fset := token.NewFileSet()
	helperUsed := false
	for _, t := range targets {
		decl, used := resetDecl(t, marked)
		helperUsed = helperUsed || used
		fmt.Fprintf(&out, "\n// %s возвращает %s в начальное состояние.\n", resetMethod, t.obj.Name())
		if err := format.Node(&out, fset, decl); err != nil {
			return nil, fmt.Errorf("печать %s.%s: %w", t.obj.Name(), resetMethod, err)
		}
		out.WriteString("\n")
	}

	if helperUsed {
		helper := targets[0].helper
		fmt.Fprintf(&out, "\n// %s присваивает значению нулевое значение его типа.\n", helper)
		if err := format.Node(&out, fset, helperDecl(helper)); err != nil {
			return nil, fmt.Errorf("печать %s: %w", helper, err)
		}
		out.WriteString("\n")
	}

	src, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("форматирование: %w", err)
	}
	return src, nil
}

// resetDecl собирает объявление метода Reset одной структуры: проверку
// приёмника на nil и операторы сброса полей.
func resetDecl(t target, marked map[*types.TypeName]bool) (*ast.FuncDecl, bool) {
	stmts, helperUsed := methodBody(t, marked)

	body := make([]ast.Stmt, 0, len(stmts)+1)
	body = append(body, &ast.IfStmt{
		Cond: &ast.BinaryExpr{X: ast.NewIdent(receiverName), Op: token.EQL, Y: ast.NewIdent("nil")},
		Body: &ast.BlockStmt{List: []ast.Stmt{&ast.ReturnStmt{}}},
	})
	body = append(body, stmts...)

	return &ast.FuncDecl{
		Recv: &ast.FieldList{List: []*ast.Field{{
			Names: []*ast.Ident{ast.NewIdent(receiverName)},
			Type:  &ast.StarExpr{X: receiverType(t.obj)},
		}}},
		Name: ast.NewIdent(resetMethod),
		Type: &ast.FuncType{Params: &ast.FieldList{}},
		Body: &ast.BlockStmt{List: body},
	}, helperUsed
}

// helperDecl собирает объявление хелпера обнуления:
//
//	func resetZero[T any](v *T) {
//		var zero T
//		*v = zero
//	}
func helperDecl(name string) *ast.FuncDecl {
	typeParam := ast.NewIdent("T")
	arg := ast.NewIdent("v")
	zero := ast.NewIdent("zero")
	return &ast.FuncDecl{
		Name: ast.NewIdent(name),
		Type: &ast.FuncType{
			TypeParams: &ast.FieldList{List: []*ast.Field{{Names: []*ast.Ident{typeParam}, Type: ast.NewIdent("any")}}},
			Params:     &ast.FieldList{List: []*ast.Field{{Names: []*ast.Ident{arg}, Type: &ast.StarExpr{X: typeParam}}}},
		},
		Body: &ast.BlockStmt{List: []ast.Stmt{
			&ast.DeclStmt{Decl: &ast.GenDecl{Tok: token.VAR, Specs: []ast.Spec{
				&ast.ValueSpec{Names: []*ast.Ident{zero}, Type: typeParam},
			}}},
			assignStmt(&ast.StarExpr{X: arg}, zero),
		}},
	}
}

// methodBody возвращает операторы сброса всех полей структуры и признак того,
// что понадобился хелпер обнуления.
func methodBody(t target, marked map[*types.TypeName]bool) (stmts []ast.Stmt, helperUsed bool) {
	for i := 0; i < t.strct.NumFields(); i++ {
		field := t.strct.Field(i)
		// поле-пустышка недоступно по имени, сбрасывать его нечем
		if field.Name() == blankField {
			continue
		}
		value := &ast.SelectorExpr{X: ast.NewIdent(receiverName), Sel: ast.NewIdent(field.Name())}
		stmt, used := resetStatement(value, field.Type(), t, marked)
		if stmt == nil {
			continue
		}
		helperUsed = helperUsed || used
		stmts = append(stmts, stmt)
	}
	return stmts, helperUsed
}

// resetStatement строит оператор сброса одного значения по правилам инкремента.
func resetStatement(value ast.Expr, typ types.Type, t target, marked map[*types.TypeName]bool) (ast.Stmt, bool) {
	// указатель сбрасывает не сам себя, а значение под ним, и только если оно есть
	if ptr, ok := typ.Underlying().(*types.Pointer); ok {
		var (
			inner ast.Stmt
			used  bool
		)
		if hasReset(typ, t, marked) {
			inner = resetCall(value)
		} else {
			inner, used = resetStatement(deref(value), ptr.Elem(), t, marked)
		}
		if inner == nil {
			return nil, false
		}
		return &ast.IfStmt{
			Cond: &ast.BinaryExpr{X: value, Op: token.NEQ, Y: ast.NewIdent("nil")},
			Body: &ast.BlockStmt{List: []ast.Stmt{inner}},
		}, used
	}

	if hasReset(typ, t, marked) {
		return resetCall(value), false
	}

	switch under := typ.Underlying().(type) {
	case *types.Basic:
		return assignStmt(value, zeroLiteral(under)), false
	case *types.Slice:
		// длина сбрасывается, ёмкость сохраняется: буфер переиспользуется
		return assignStmt(value, &ast.SliceExpr{X: value, High: &ast.BasicLit{Kind: token.INT, Value: "0"}}), false
	case *types.Map:
		return callStmt(ast.NewIdent("clear"), value), false
	default:
		return callStmt(ast.NewIdent(t.helper), addressOf(value)), true
	}
}

// deref оборачивает выражение разыменованием, сохраняя приоритет операций:
// (*x.f)[:0] — это срез значения, а *x.f[:0] — срез указателя.
func deref(value ast.Expr) ast.Expr {
	return &ast.ParenExpr{X: &ast.StarExpr{X: value}}
}

// addressOf берёт адрес выражения. Адрес разыменования схлопывается обратно в
// исходный указатель прямо на дереве: &(*p) — это p.
func addressOf(value ast.Expr) ast.Expr {
	if paren, ok := value.(*ast.ParenExpr); ok {
		if star, ok := paren.X.(*ast.StarExpr); ok {
			return star.X
		}
	}
	return &ast.UnaryExpr{Op: token.AND, X: value}
}

// resetCall строит вызов метода Reset у значения value.
func resetCall(value ast.Expr) ast.Stmt {
	return callStmt(&ast.SelectorExpr{X: value, Sel: ast.NewIdent(resetMethod)})
}

// callStmt строит оператор-вызов функции fun с аргументами args.
func callStmt(fun ast.Expr, args ...ast.Expr) ast.Stmt {
	return &ast.ExprStmt{X: &ast.CallExpr{Fun: fun, Args: args}}
}

// assignStmt строит присваивание значения value выражению dst.
func assignStmt(dst, value ast.Expr) ast.Stmt {
	return &ast.AssignStmt{Lhs: []ast.Expr{dst}, Tok: token.ASSIGN, Rhs: []ast.Expr{value}}
}

// hasReset сообщает, есть ли у типа метод Reset без аргументов и возвращаемых
// значений. Структуры, помеченные маркером, тоже считаются: их методы
// появятся в этом же запуске генератора.
//
// Интерфейсы исключены: значение интерфейса по умолчанию nil, и вызов метода на
// нём паникует, поэтому такое поле обнуляется, а не сбрасывается.
func hasReset(typ types.Type, t target, marked map[*types.TypeName]bool) bool {
	if _, ok := typ.Underlying().(*types.Interface); ok {
		return false
	}
	if named, ok := typ.(*types.Named); ok && marked[named.Obj()] {
		return true
	}
	if ptr, ok := typ.Underlying().(*types.Pointer); ok {
		if named, ok := ptr.Elem().(*types.Named); ok && marked[named.Obj()] {
			return true
		}
	}

	obj, _, _ := types.LookupFieldOrMethod(typ, true, t.pkg.Types, resetMethod)
	fn, ok := obj.(*types.Func)
	if !ok {
		return false
	}
	sig, ok := fn.Type().(*types.Signature)
	if !ok || sig.Params().Len() != 0 || sig.Results().Len() != 0 {
		return false
	}
	// метод из прошлого результата генерации не в счёт: маркер могли снять, и
	// тогда после перезаписи такого метода не станет
	path, err := filepath.Abs(t.pkg.Fset.Position(fn.Pos()).Filename)
	if err != nil {
		return false
	}
	_, fromGenerated := t.generated[path]
	return !fromGenerated
}

// zeroLiteral возвращает литерал нулевого значения примитивного типа.
func zeroLiteral(basic *types.Basic) ast.Expr {
	switch info := basic.Info(); {
	case info&types.IsBoolean != 0:
		return ast.NewIdent("false")
	case info&types.IsString != 0:
		return &ast.BasicLit{Kind: token.STRING, Value: `""`}
	case info&types.IsComplex != 0:
		return &ast.BasicLit{Kind: token.IMAG, Value: "0i"}
	case info&types.IsNumeric != 0:
		return &ast.BasicLit{Kind: token.INT, Value: "0"}
	default:
		// unsafe.Pointer и прочие нечисловые примитивы
		return ast.NewIdent("nil")
	}
}
