package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/tools/go/packages"
)

const (
	// generateMarker — комментарий над структурой, включающий генерацию.
	generateMarker = "generate:reset"
	// resetMethod — имя генерируемого метода.
	resetMethod = "Reset"
	// genFileName — файл с методами всех помеченных структур пакета.
	genFileName = "reset.gen.go"
	// receiverName — имя приёмника в сгенерированном методе.
	receiverName = "x"
	// zeroHelperName — хелпер обнуления через дженерик: избавляет
	// сгенерированный файл от импортов чужих пакетов.
	zeroHelperName = "resetZero"
	// blankField — поле-пустышка, к которому нельзя обратиться по имени.
	blankField = "_"
	// scanPattern — шаблон загрузки пакетов текущего модуля и ниже.
	scanPattern = "./..."
	// genFilePerm — права на сгенерированный файл.
	genFilePerm = 0o644
	// genHeader предупреждает, что файл не редактируют руками.
	genHeader = "// Code generated by \"go run ./cmd/reset\"; DO NOT EDIT."
)

// packagesMode перечисляет данные, нужные генератору: имена и файлы пакетов,
// разобранные деревья и результаты вывода типов.
const packagesMode = packages.NeedName | packages.NeedFiles | packages.NeedSyntax |
	packages.NeedTypes | packages.NeedTypesInfo

// target — структура, помеченная к генерации.
type target struct {
	obj    *types.TypeName
	strct  *types.Struct
	pkg    *packages.Package
	dir    string
	helper string
}

// generate сканирует пакеты начиная с dir и записывает файлы с методами Reset.
// Возвращает пути записанных файлов.
func generate(dir string) ([]string, error) {
	// прошлые результаты удаляются до разбора: иначе снятый маркер оставил бы
	// метод навсегда, а удалённая структура сделала бы пакет неразбираемым
	if err := removeGenerated(dir); err != nil {
		return nil, err
	}

	pkgs, err := packages.Load(&packages.Config{Mode: packagesMode, Dir: dir}, scanPattern)
	if err != nil {
		return nil, fmt.Errorf("загрузка пакетов: %w", err)
	}

	var targets []target
	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 {
			return nil, fmt.Errorf("пакет %s: %w", pkg.PkgPath, pkg.Errors[0])
		}
		found, err := markedStructs(pkg)
		if err != nil {
			return nil, err
		}
		targets = append(targets, found...)
	}

	// структура, помеченная к генерации, получит Reset в этом же запуске,
	// поэтому вложенные поля такого типа сбрасываются вызовом метода
	marked := make(map[*types.TypeName]bool, len(targets))
	for _, t := range targets {
		marked[t.obj] = true
	}

	byDir := make(map[string][]target)
	for _, t := range targets {
		byDir[t.dir] = append(byDir[t.dir], t)
	}

	written := make([]string, 0, len(byDir))
	for dir, dirTargets := range byDir {
		path := filepath.Join(dir, genFileName)
		src, err := renderFile(dirTargets, marked)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		if err := os.WriteFile(path, src, genFilePerm); err != nil {
			return nil, fmt.Errorf("запись %s: %w", path, err)
		}
		written = append(written, path)
	}
	sort.Strings(written)

	return written, nil
}

// markedStructs собирает структуры пакета, над которыми стоит маркер генерации.
func markedStructs(pkg *packages.Package) ([]target, error) {
	var found []target
	for _, file := range pkg.Syntax {
		dir := filepath.Dir(pkg.Fset.Position(file.Pos()).Filename)
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok || !hasMarker(genDecl.Doc, typeSpec.Doc) {
					continue
				}
				obj, ok := pkg.TypesInfo.Defs[typeSpec.Name].(*types.TypeName)
				if !ok {
					continue
				}
				strct, ok := obj.Type().Underlying().(*types.Struct)
				if !ok {
					continue
				}
				// метод, написанный руками, генератор не заменяет: два
				// объявления Reset сделали бы пакет несобираемым
				if hasOwnReset(obj, pkg.Types) {
					return nil, fmt.Errorf("%s.%s: метод %s уже объявлен, маркер %s лишний",
						pkg.PkgPath, obj.Name(), resetMethod, generateMarker)
				}
				found = append(found, target{
					obj:    obj,
					strct:  strct,
					pkg:    pkg,
					dir:    dir,
					helper: helperName(pkg),
				})
			}
		}
	}
	return found, nil
}

// removeGenerated удаляет ранее сгенерированные файлы во всём дереве каталогов.
// Чужие файлы с тем же именем не трогаются: удаляются только те, что начинаются
// с нашего заголовка.
func removeGenerated(root string) error {
	return filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || entry.Name() != genFileName {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("чтение %s: %w", path, err)
		}
		if !strings.HasPrefix(string(data), genHeader) {
			return nil
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("удаление %s: %w", path, err)
		}
		return nil
	})
}

// hasOwnReset сообщает, объявлен ли метод Reset в исходном коде пакета.
func hasOwnReset(obj *types.TypeName, pkg *types.Package) bool {
	named, ok := obj.Type().(*types.Named)
	if !ok {
		return false
	}
	fn, _, _ := types.LookupFieldOrMethod(types.NewPointer(named), true, pkg, resetMethod)
	_, ok = fn.(*types.Func)
	return ok
}

// hasMarker ищет маркер в комментариях объявления типа: он может стоять и над
// одиночным type, и над строкой внутри блока type (...).
func hasMarker(groups ...*ast.CommentGroup) bool {
	for _, group := range groups {
		if group == nil {
			continue
		}
		for _, comment := range group.List {
			if strings.Contains(comment.Text, generateMarker) {
				return true
			}
		}
	}
	return false
}

// helperName подбирает имя хелпера, не занятое в пакете: к базовому имени
// добавляется числовой суффикс, пока имя не окажется свободным.
func helperName(pkg *packages.Package) string {
	name := zeroHelperName
	for i := 2; pkg.Types.Scope().Lookup(name) != nil; i++ {
		name = zeroHelperName + strconv.Itoa(i)
	}
	return name
}

// receiver печатает приёмник метода. У обобщённой структуры перечисляются
// параметры типа: func (x *Box[T]) Reset().
func receiver(obj *types.TypeName) string {
	named, ok := obj.Type().(*types.Named)
	if !ok || named.TypeParams().Len() == 0 {
		return obj.Name()
	}
	params := named.TypeParams()
	names := make([]string, 0, params.Len())
	for i := 0; i < params.Len(); i++ {
		names = append(names, params.At(i).Obj().Name())
	}
	return obj.Name() + "[" + strings.Join(names, ", ") + "]"
}

// renderFile собирает содержимое reset.gen.go для одного пакета.
func renderFile(targets []target, marked map[*types.TypeName]bool) ([]byte, error) {
	sort.Slice(targets, func(i, j int) bool { return targets[i].obj.Name() < targets[j].obj.Name() })

	var body strings.Builder
	helperUsed := false
	for _, t := range targets {
		stmts, used := methodBody(t, marked)
		helperUsed = helperUsed || used

		fmt.Fprintf(&body, "\n// %s возвращает %s в начальное состояние.\n", resetMethod, t.obj.Name())
		fmt.Fprintf(&body, "func (%s *%s) %s() {\n", receiverName, receiver(t.obj), resetMethod)
		fmt.Fprintf(&body, "if %s == nil {\nreturn\n}\n", receiverName)
		for _, stmt := range stmts {
			body.WriteString(stmt)
			body.WriteString("\n")
		}
		body.WriteString("}\n")
	}

	var out strings.Builder
	out.WriteString(genHeader)
	out.WriteString("\n\npackage ")
	out.WriteString(targets[0].pkg.Types.Name())
	out.WriteString("\n")
	out.WriteString(body.String())

	if helperUsed {
		helper := targets[0].helper
		fmt.Fprintf(&out, "\n// %s присваивает значению нулевое значение его типа.\n", helper)
		fmt.Fprintf(&out, "func %s[T any](v *T) {\nvar zero T\n*v = zero\n}\n", helper)
	}

	src, err := format.Source([]byte(out.String()))
	if err != nil {
		return nil, fmt.Errorf("форматирование: %w", err)
	}
	return src, nil
}

// methodBody возвращает операторы сброса всех полей структуры и признак того,
// что понадобился хелпер обнуления.
func methodBody(t target, marked map[*types.TypeName]bool) (stmts []string, helperUsed bool) {
	for i := 0; i < t.strct.NumFields(); i++ {
		field := t.strct.Field(i)
		// поле-пустышка недоступно по имени, сбрасывать его нечем
		if field.Name() == blankField {
			continue
		}
		selector := receiverName + "." + field.Name()
		stmt, used := resetStatement(selector, field.Type(), t, marked)
		if stmt == "" {
			continue
		}
		helperUsed = helperUsed || used
		stmts = append(stmts, stmt)
	}
	return stmts, helperUsed
}

// resetStatement строит оператор сброса одного значения по правилам инкремента.
func resetStatement(selector string, typ types.Type, t target, marked map[*types.TypeName]bool) (string, bool) {
	// указатель сбрасывает не сам себя, а значение под ним, и только если оно есть
	if ptr, ok := typ.Underlying().(*types.Pointer); ok {
		var (
			inner string
			used  bool
		)
		if hasReset(typ, t.pkg.Types, marked) {
			inner = selector + "." + resetMethod + "()"
		} else {
			inner, used = resetStatement(deref(selector), ptr.Elem(), t, marked)
		}
		if inner == "" {
			return "", false
		}
		return fmt.Sprintf("if %s != nil {\n%s\n}", selector, inner), used
	}

	if hasReset(typ, t.pkg.Types, marked) {
		return selector + "." + resetMethod + "()", false
	}

	switch under := typ.Underlying().(type) {
	case *types.Basic:
		return fmt.Sprintf("%s = %s", selector, zeroLiteral(under)), false
	case *types.Slice:
		// длина сбрасывается, ёмкость сохраняется: буфер переиспользуется
		return fmt.Sprintf("%s = %s[:0]", selector, selector), false
	case *types.Map:
		return fmt.Sprintf("clear(%s)", selector), false
	default:
		return fmt.Sprintf("%s(%s)", t.helper, addressOf(selector)), true
	}
}

// deref оборачивает выражение разыменованием, сохраняя приоритет операций:
// (*x.f)[:0] — это срез значения, а *x.f[:0] — срез указателя.
func deref(selector string) string {
	return "(*" + selector + ")"
}

// addressOf берёт адрес выражения, схлопывая &(*p) обратно в p.
func addressOf(selector string) string {
	if inner, ok := strings.CutPrefix(selector, "(*"); ok {
		if inner, ok := strings.CutSuffix(inner, ")"); ok {
			return inner
		}
	}
	return "&" + selector
}

// hasReset сообщает, есть ли у типа метод Reset без аргументов и возвращаемых
// значений. Структуры, помеченные маркером, тоже считаются: их методы
// появятся в этом же запуске генератора.
//
// Интерфейсы исключены: значение интерфейса по умолчанию nil, и вызов метода на
// нём паникует, поэтому такое поле обнуляется, а не сбрасывается.
func hasReset(typ types.Type, pkg *types.Package, marked map[*types.TypeName]bool) bool {
	if _, ok := typ.Underlying().(*types.Interface); ok {
		return false
	}
	if named, ok := typ.(*types.Named); ok && marked[named.Obj()] {
		return true
	}
	if ptr, ok := typ.Underlying().(*types.Pointer); ok {
		if named, ok := ptr.Elem().(*types.Named); ok && marked[named.Obj()] {
			return true
		}
	}

	obj, _, _ := types.LookupFieldOrMethod(typ, true, pkg, resetMethod)
	fn, ok := obj.(*types.Func)
	if !ok {
		return false
	}
	sig, ok := fn.Type().(*types.Signature)
	return ok && sig.Params().Len() == 0 && sig.Results().Len() == 0
}

// zeroLiteral возвращает литерал нулевого значения примитивного типа.
func zeroLiteral(basic *types.Basic) string {
	switch info := basic.Info(); {
	case info&types.IsBoolean != 0:
		return "false"
	case info&types.IsString != 0:
		return `""`
	case info&types.IsComplex != 0:
		return "0i"
	case info&types.IsNumeric != 0:
		return "0"
	default:
		// unsafe.Pointer и прочие нечисловые примитивы
		return "nil"
	}
}
